# Generated by Django 3.2.22 on 2023-10-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_food', '0002_auto_20231014_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
